[package]
name = "listener"
version = "0.1.0"
authors = ["Noah <noah@coronasoftware.net>"]
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.114" }
yew = { version = "0.19" }
yewdux = { path = "../../crates/yewdux" }
